# Generated by Django 5.1.15 on 2026-09-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_family', models.CharField(blank=True, max_length=100, null=True)),
                ('model_size_category', models.CharField(blank=True, max_length=50, null=True)),
                ('output_description', models.CharField(max_length=255)),
                ('output_tokens', models.PositiveIntegerField()),
                ('energy_mwh', models.FloatField(help_text='Estimation Ecologits en mWh (§9).')),
                ('source', models.CharField(default='Ecologits', max_length=100)),
                ('prompt_template', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['provider', 'model_name', 'output_tokens'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_played', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIGURATION', 'Configuration'), ('BIKE_CHECK', 'Vérification du vélo'), ('INTRODUCTION', 'Introduction pédagogique'), ('SPINNING', 'Tirage (roues)'), ('TEAM_SELECTION', 'Sélection du coureur'), ('PREPARATION', 'Préparation'), ('CYCLING', 'Pédalage'), ('RESULT', 'Résultat de la manche'), ('NEXT_TEAM', 'Équipe suivante'), ('FINAL_RESULTS', 'Résultats finaux'), ('PEDAGOGICAL_SUMMARY', 'Synthèse pédagogique')], default='CONFIGURATION', max_length=30)),
                ('current_round_number', models.IntegerField(default=0)),
                ('players_per_team', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.player')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.team'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revolutions', models.IntegerField(default=0)),
                ('human_energy_joules', models.FloatField(default=0)),
                ('target_energy_mwh', models.FloatField()),
                ('performance_percent', models.FloatField(default=0)),
                ('tier_reached', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=60)),
                ('generation_text', models.TextField(blank=True, default='')),
                ('generation_simulated', models.BooleanField(default=True)),
                ('generation_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.energyscenario')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
            options={
                'ordering': ['game', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('game', 'player'), name='unique_player_round_per_game')],
            },
        ),
    ]
